#' @importFrom utils head
NULL

# ── Professional theme ──────────────────────────────────────

.theme_sef <- function(base_size = 11) {
  ggplot2::theme_minimal(base_size = base_size) %+replace%
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = base_size + 3, hjust = 0),
      plot.subtitle = ggplot2::element_text(colour = "grey40", size = base_size, hjust = 0,
                                             margin = ggplot2::margin(b = 10)),
      plot.caption = ggplot2::element_text(colour = "grey50", size = base_size - 2, hjust = 1,
                                            face = "italic"),
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_line(colour = "grey92"),
      legend.position = "right",
      legend.title = ggplot2::element_text(face = "bold", size = base_size - 1),
      axis.title = ggplot2::element_text(face = "bold"),
      plot.margin = ggplot2::margin(15, 15, 10, 10)
    )
}

.sef_caption <- function() {
  paste0("Generated by palimpsestr ", as.character(utils::packageVersion("palimpsestr")))
}

# ── Colour palettes (colour-blind safe) ──

.phase_colours <- function(k) {
  pal <- c("#E69F00", "#56B4E9", "#009E73", "#CC79A7", "#D55E00", "#0072B2", "#F0E442", "#999999")
  pal[seq_len(min(k, length(pal)))]
}

.viridis_c <- function(name, option = "viridis", direction = 1) {
  tryCatch(
    ggplot2::scale_colour_viridis_c(name = name, option = option, direction = direction),
    error = function(e) ggplot2::scale_colour_gradient(low = "#440154", high = "#FDE725", name = name)
  )
}

.viridis_f <- function(name, option = "viridis", direction = 1) {
  tryCatch(
    ggplot2::scale_fill_viridis_c(name = name, option = option, direction = direction),
    error = function(e) ggplot2::scale_fill_gradient(low = "#440154", high = "#FDE725", name = name)
  )
}


# ══════════════════════════════════════════════════════════════
# PUBLIC PLOT FUNCTIONS
# ══════════════════════════════════════════════════════════════

#' Phase assignment map
#'
#' Plots artefact positions coloured by dominant phase, with point size
#' proportional to assignment confidence.
#'
#' @param object A \code{sef_fit} object.
#' @param xlabel,ylabel Axis labels (default: "Easting (m)" / "Northing (m)").
#' @return A ggplot object.
#' @seealso \code{\link{plot_phasefield}} for base R version,
#'   \code{\link{as_plotly}} for interactive version.
#' @family plotting
#' @export
gg_phasefield <- function(object, xlabel = "Easting (m)", ylabel = "Northing (m)") {
  if (!inherits(object, "sef_fit")) stop("object must be a sef_fit", call. = FALSE)
  .check_ggplot()
  df <- data.frame(
    x = object$data[[object$coords[1]]],
    y = object$data[[object$coords[2]]],
    phase = factor(object$phase),
    confidence = apply(object$phase_prob, 1, max)
  )
  k <- object$k
  n <- nrow(df)

  ggplot2::ggplot(df, ggplot2::aes(x = .data$x, y = .data$y,
                                    colour = .data$phase, size = .data$confidence)) +
    ggplot2::geom_point(alpha = 0.8, stroke = 0.3) +
    ggplot2::scale_colour_manual(
      values = .phase_colours(k), name = "Depositional\nPhase",
      labels = paste0("Phase ", seq_len(k), " (n=", table(df$phase), ")")
    ) +
    ggplot2::scale_size_continuous(
      range = c(1.5, 5), name = "Assignment\nConfidence",
      labels = function(x) sprintf("%.0f%%", x * 100)
    ) +
    ggplot2::coord_equal() +
    ggplot2::labs(
      title = "Dominant Phase Assignment",
      subtitle = sprintf("%d finds assigned to %d depositional phases | PDI = %.3f",
                         n, k, pdi(object)),
      x = xlabel, y = ylabel,
      caption = .sef_caption()
    ) +
    .theme_sef()
}


#' Spatial entropy map
#'
#' Shows Shannon entropy of phase probabilities across the excavation area.
#' High entropy = uncertain phase assignment (possible palimpsest zone).
#'
#' @param object A \code{sef_fit} object.
#' @param xlabel,ylabel Axis labels.
#' @return A ggplot object.
#' @seealso \code{\link{plot_entropy}} for base R version,
#'   \code{\link{as_plotly}} for interactive version.
#' @family plotting
#' @export
gg_entropy <- function(object, xlabel = "Easting (m)", ylabel = "Northing (m)") {
  if (!inherits(object, "sef_fit")) stop("object must be a sef_fit", call. = FALSE)
  .check_ggplot()
  df <- data.frame(
    x = object$data[[object$coords[1]]],
    y = object$data[[object$coords[2]]],
    entropy = object$entropy
  )

  ggplot2::ggplot(df, ggplot2::aes(x = .data$x, y = .data$y, colour = .data$entropy)) +
    ggplot2::geom_point(size = 3.5, alpha = 0.85) +
    .viridis_c("Shannon\nEntropy H", option = "inferno") +
    ggplot2::coord_equal() +
    ggplot2::labs(
      title = "Spatial Entropy Map",
      subtitle = paste0(
        "Entropy measures uncertainty in phase assignment\n",
        "Dark = confident assignment | Bright = ambiguous (possible mixing zone)"
      ),
      x = xlabel, y = ylabel,
      caption = .sef_caption()
    ) +
    .theme_sef()
}


#' Excavation Stratigraphic Energy map
#'
#' Shows ESE values across space. High energy indicates zones where
#' neighbouring artefacts are dissimilar (depositional disruption).
#'
#' @param object A \code{sef_fit} object.
#' @param xlabel,ylabel Axis labels.
#' @return A ggplot object.
#' @seealso \code{\link{gg_entropy}},
#'   \code{\link{as_plotly}} for interactive version.
#' @family plotting
#' @export
gg_energy <- function(object, xlabel = "Easting (m)", ylabel = "Northing (m)") {
  if (!inherits(object, "sef_fit")) stop("object must be a sef_fit", call. = FALSE)
  .check_ggplot()
  df <- data.frame(
    x = object$data[[object$coords[1]]],
    y = object$data[[object$coords[2]]],
    energy = object$energy
  )

  ggplot2::ggplot(df, ggplot2::aes(x = .data$x, y = .data$y, colour = .data$energy)) +
    ggplot2::geom_point(size = 3.5, alpha = 0.85) +
    .viridis_c("ESE\n(Energy)", option = "magma") +
    ggplot2::coord_equal() +
    ggplot2::labs(
      title = "Excavation Stratigraphic Energy (ESE)",
      subtitle = paste0(
        "Energy measures local depositional disruption\n",
        "Dark = stable deposit | Bright = mixing zone (bioturbation, redeposition)"
      ),
      x = xlabel, y = ylabel,
      caption = .sef_caption()
    ) +
    .theme_sef()
}


#' Intrusion probability map
#'
#' Maps the probability that each find is an intrusion (displaced or
#' redeposited). Top suspects are circled and labelled.
#'
#' @param object A \code{sef_fit} object.
#' @param top_n Number of top intrusions to label.
#' @param xlabel,ylabel Axis labels.
#' @return A ggplot object.
#' @seealso \code{\link{detect_intrusions}},
#'   \code{\link{as_plotly}} for interactive version.
#' @family plotting
#' @export
gg_intrusions <- function(object, top_n = 5,
                           xlabel = "Easting (m)", ylabel = "Northing (m)") {
  if (!inherits(object, "sef_fit")) stop("object must be a sef_fit", call. = FALSE)
  .check_ggplot()
  di <- detect_intrusions(object)
  n_susp <- sum(di$intrusion_prob > 0.5)
  df <- data.frame(
    x = object$data[[object$coords[1]]],
    y = object$data[[object$coords[2]]],
    intr = di$intrusion_prob,
    id = di$id
  )
  top <- df[order(df$intr, decreasing = TRUE), ][seq_len(min(top_n, nrow(df))), ]

  p <- ggplot2::ggplot(df, ggplot2::aes(x = .data$x, y = .data$y, colour = .data$intr)) +
    ggplot2::geom_point(size = 3, alpha = 0.8) +
    .viridis_c("Intrusion\nProbability", option = "rocket", direction = -1) +
    ggplot2::geom_point(data = top, shape = 1, size = 6, colour = "black", stroke = 1.2) +
    ggplot2::geom_text(data = top, ggplot2::aes(label = .data$id),
                        colour = "black", size = 2.8, hjust = -0.3, vjust = -0.5) +
    ggplot2::coord_equal() +
    ggplot2::labs(
      title = "Intrusion Detection Map",
      subtitle = sprintf(
        "%d finds flagged (prob > 0.5) | Circled: top %d suspects\n%s",
        n_susp, min(top_n, nrow(df)),
        "Score combines high entropy + high energy + low network connectivity"
      ),
      x = xlabel, y = ylabel,
      caption = .sef_caption()
    ) +
    .theme_sef()
  p
}


#' Phase count selection diagnostics
#'
#' Three-panel plot showing BIC, PDI, and Mean Entropy for different K values.
#'
#' @param ck Data.frame from \code{compare_k()}.
#' @return A ggplot object.
#' @seealso \code{\link{compare_k}}
#' @family plotting
#' @export
gg_compare_k <- function(ck) {
  .check_ggplot()
  best <- ck$k[which.min(ck$bic)]
  df_long <- data.frame(
    k = rep(ck$k, 3),
    value = c(ck$bic, ck$pdi, ck$mean_entropy),
    metric = factor(
      rep(c("BIC (lower = better fit)",
            "PDI (higher = better separation)",
            "Mean Entropy (lower = more confident)"), each = nrow(ck)),
      levels = c("BIC (lower = better fit)",
                 "PDI (higher = better separation)",
                 "Mean Entropy (lower = more confident)")
    )
  )

  ggplot2::ggplot(df_long, ggplot2::aes(x = .data$k, y = .data$value)) +
    ggplot2::geom_line(linewidth = 0.9, colour = "#0072B2") +
    ggplot2::geom_point(size = 3.5, colour = "#0072B2") +
    ggplot2::geom_vline(xintercept = best, linetype = "dashed",
                         colour = "#D55E00", linewidth = 0.7) +
    ggplot2::annotate("text", x = best + 0.15, y = Inf, label = paste("K =", best),
                       colour = "#D55E00", vjust = 2, hjust = 0, fontface = "bold", size = 3.5) +
    ggplot2::facet_wrap(~ metric, scales = "free_y", nrow = 1) +
    ggplot2::scale_x_continuous(breaks = ck$k) +
    ggplot2::labs(
      title = "Phase Count Selection",
      subtitle = sprintf("Comparing K = %d to %d | Optimal K = %d (minimum BIC)",
                         min(ck$k), max(ck$k), best),
      x = "Number of Phases (K)", y = NULL,
      caption = .sef_caption()
    ) +
    .theme_sef() +
    ggplot2::theme(strip.text = ggplot2::element_text(face = "bold", size = 10))
}


#' Overlay SEF results on excavation plan geometries
#'
#' Displays SEF analysis results directly on the excavation plan.
#' Polygons represent stratigraphic units; points represent individual finds.
#'
#' @param object A \code{sef_fit} object.
#' @param geometries An sf object with excavation plan polygons.
#'   Must contain a \code{us} column matching \code{context} values in the data.
#' @param layer What to display: \code{"phase"}, \code{"entropy"},
#'   \code{"energy"}, or \code{"intrusion"}.
#' @param show_labels Show US labels on polygons.
#' @param show_points Overlay individual finds as points.
#' @param xlabel,ylabel Axis labels (default: NULL = use CRS units).
#' @return A ggplot object.
#' @seealso \code{\link{load_geometries}}, \code{\link{as_sf_phase}}
#' @family plotting
#' @export
gg_map <- function(object, geometries,
                   layer = c("phase", "entropy", "energy", "intrusion"),
                   show_labels = TRUE, show_points = TRUE,
                   xlabel = NULL, ylabel = NULL) {
  if (!inherits(object, "sef_fit")) stop("object must be a sef_fit", call. = FALSE)
  if (!requireNamespace("sf", quietly = TRUE)) stop("Package 'sf' is required.", call. = FALSE)
  .check_ggplot()
  layer <- match.arg(layer)

  pdt <- phase_diagnostic_table(object)
  di <- detect_intrusions(object)

  # Aggregate per-US stats
  ctx_vec <- object$data[["context"]]
  us_stats <- data.frame(
    us = tapply(ctx_vec, ctx_vec, function(x) x[1]),
    mean_entropy = tapply(pdt$entropy, ctx_vec, mean),
    mean_energy = tapply(pdt$energy, ctx_vec, mean),
    mean_intr = tapply(di$intrusion_prob, ctx_vec, mean),
    stringsAsFactors = FALSE
  )
  phase_mode <- tapply(pdt$dominant_phase, ctx_vec, function(x) {
    as.integer(names(sort(table(x), decreasing = TRUE))[1])
  })
  us_stats$dominant_phase <- factor(phase_mode[us_stats$us])

  # Merge with geometries
  idx <- match(geometries$context, us_stats$us); gd <- geometries; gd$mean_entropy <- us_stats$mean_entropy[idx]; gd$mean_energy <- us_stats$mean_energy[idx]; gd$mean_intr <- us_stats$mean_intr[idx]; gd$dominant_phase <- us_stats$dominant_phase[idx]

  # Point data
  pts <- data.frame(
    x = object$data[[object$coords[1]]],
    y = object$data[[object$coords[2]]],
    phase = factor(pdt$dominant_phase),
    entropy = pdt$entropy,
    energy = pdt$energy,
    intr = di$intrusion_prob
  )

  # Subtitle map
  sub_map <- c(
    phase = "US polygons coloured by dominant phase | Points = individual finds",
    entropy = "Dark = confident attribution | Bright = uncertain (possible palimpsest)",
    energy = "Dark = stable deposit | Bright = disruption zone",
    intrusion = "Dark = in situ | Bright = likely displaced or redeposited"
  )
  title_map <- c(
    phase = "Phase Assignment on Excavation Plan",
    entropy = "Entropy Map on Excavation Plan",
    energy = "Energy Map on Excavation Plan",
    intrusion = "Intrusion Map on Excavation Plan"
  )

  p <- ggplot2::ggplot()

  if (layer == "phase") {
    k <- object$k
    p <- p +
      ggplot2::geom_sf(data = gd, ggplot2::aes(fill = .data$dominant_phase),
                        colour = "grey30", linewidth = 0.4, alpha = 0.45) +
      ggplot2::scale_fill_manual(values = .phase_colours(k), name = "Phase (US)",
                                  na.value = "grey90", drop = FALSE)
    if (show_points) {
      p <- p + ggplot2::geom_point(data = pts,
                                     ggplot2::aes(x = .data$x, y = .data$y, colour = .data$phase),
                                     size = 2.2, alpha = 0.9, stroke = 0.3) +
        ggplot2::scale_colour_manual(values = .phase_colours(k), name = "Phase (Find)",
                                      drop = FALSE)
    }
  } else {
    fill_col <- switch(layer, entropy = "mean_entropy", energy = "mean_energy", intrusion = "mean_intr")
    fill_name <- switch(layer,
                        entropy = "Mean\nEntropy",
                        energy = "Mean\nESE",
                        intrusion = "Mean\nIntrusion Prob.")
    opt <- switch(layer, entropy = "inferno", energy = "magma", intrusion = "rocket")
    dir <- if (layer == "intrusion") -1 else 1

    p <- p +
      ggplot2::geom_sf(data = gd, ggplot2::aes(fill = .data[[fill_col]]),
                        colour = "grey30", linewidth = 0.4, alpha = 0.65) +
      .viridis_f(name = fill_name, option = opt, direction = dir)
  }

  if (show_labels && nrow(gd) <= 80) {
    centroids <- suppressWarnings(sf::st_centroid(gd))
    coords <- sf::st_coordinates(centroids)
    lbl <- data.frame(x = coords[, 1], y = coords[, 2],
                       us = gsub("^US_", "", gd$us))
    p <- p + ggplot2::geom_text(data = lbl,
                                 ggplot2::aes(x = .data$x, y = .data$y, label = .data$us),
                                 size = 2.0, colour = "grey20", fontface = "bold", alpha = 0.6)
  }

  p + ggplot2::coord_sf() +
    ggplot2::labs(
      title = title_map[layer],
      subtitle = sub_map[layer],
      x = xlabel, y = ylabel,
      caption = .sef_caption()
    ) +
    .theme_sef() +
    ggplot2::theme(axis.text = ggplot2::element_text(size = 8))
}


# ── Utility ──

.check_ggplot <- function() {
  if (!requireNamespace("ggplot2", quietly = TRUE))
    stop("Package 'ggplot2' is required for gg_* functions.", call. = FALSE)
}

.check_plotly <- function() {
  if (!requireNamespace("plotly", quietly = TRUE))
    stop("Package 'plotly' is required for as_plotly().", call. = FALSE)
}

.build_tooltip <- function(object) {
  di <- detect_intrusions(object)
  prob_max <- apply(object$phase_prob, 1, max)
  sprintf(
    "ID: %s\nContext: %s\nPhase: %d (prob: %.1f%%)\nDating: %.0f\u2013%.0f\nClass: %s\nEntropy: %.3f\nEnergy: %.3f\nIntrusion: %.1f%%",
    if ("id" %in% names(object$data)) object$data$id else seq_len(nrow(object$data)),
    if (!is.null(object$context)) object$data[[object$context]] else "\u2014",
    object$phase,
    prob_max * 100,
    object$data[[object$chrono[1]]],
    object$data[[object$chrono[2]]],
    object$data[[object$class_col]],
    object$entropy,
    object$energy,
    di$intrusion_prob * 100
  )
}

#' Convert a ggplot to an interactive plotly widget
#'
#' Wraps \code{\link[plotly]{ggplotly}} with archaeological tooltips showing
#' find ID, context, phase probability, dating, class, entropy, and energy.
#'
#' @param gg A ggplot object produced by any \code{gg_*} function.
#' @param tooltip Character vector of aesthetics to show. Defaults to
#'   \code{"text"} which displays the enriched archaeological tooltip.
#' @param ... Additional arguments passed to \code{\link[plotly]{ggplotly}}.
#' @return A \code{plotly} htmlwidget object.
#' @seealso \code{\link{gg_phasefield}}, \code{\link{gg_entropy}},
#'   \code{\link{gg_energy}}, \code{\link{gg_intrusions}}
#' @family plotting
#' @examples
#' \donttest{
#' x <- archaeo_sim(n = 80, k = 3, seed = 1)
#' fit <- fit_sef(x, k = 3)
#' if (requireNamespace("ggplot2", quietly = TRUE) &&
#'     requireNamespace("plotly", quietly = TRUE)) {
#'   p <- as_plotly(gg_phasefield(fit))
#' }
#' }
#' @export
as_plotly <- function(gg, tooltip = "text", ...) {
  .check_plotly()
  if (!inherits(gg, "gg")) stop("gg must be a ggplot object", call. = FALSE)
  plotly::ggplotly(gg, tooltip = tooltip, ...)
}
